### ISSUE TITLE
Small documentation request

### ISSUE THREAD

**Issue by jhabdas** [OpusCapitaBES/js-react-showroom-client#3]
> We are sure you are clever men.

Though I'm not one of them (I think), some of the [970 React contributors currently](https://github.com/facebook/react/graphs/contributors) may not identify as men. Could we <del>men</del> from the README? I'd do it myself but I'm on a limited data plan and currently mobile.

**Comment by kvolkovich-sc** [comment]
:man_facepalming: :woman_facepalming: You're right. It a bit similar to sexism.
Fixed and closed. https://github.com/OpusCapitaBES/js-react-showroom-client/commit/539800831668f9c6b1d9281ad07cf032992d7c9b

**Comment by jhabdas** [comment]
@kvolkovich-sc tyvm for your quick response
